

let serviceContent = [
    {
     index: 1,
     header: "Cloud \n Services",
     Content: ` love youLorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam 
     \n
     ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.`},
    {
     index: 2,
     header: "Security",
     Content: `love youLorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi 
     \n
     purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.`},
    {
     index: 3,
     header: "App Services",
     Content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.`},
    {
     index: 4,
     header: "Collaboration",
     Content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.`},
    {
     index: 5,
     header: "Training",
     Content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis ultrices interdum. Mauris ultrices nisi purus, in blandit leo placerat ac. Nulla finibus leo eu ligula auctor vehicula. Etiam non sollicitudin urna. Sed a quam ultrices, dapibus risus nec, posuere quam. Donec a luctus nibh. Donec nisi enim, varius porttitor dictum eu, congue in risus. Donec sed metus urna. Donec auctor porta felis imperdiet cursus. Donec felis enim, vehicula nec euismod ut, interdum et ligula.`}
]

export default serviceContent;

